services:
  api:
    build:
      context: ../..
      dockerfile: code/deployment/api/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../../models:/app/models
    restart: unless-stopped

  app:
    build:
      context: ../..
      dockerfile: code/deployment/app/Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - api
    environment:
      - API_URL=http://api:8000
    restart: unless-stopped